### ISSUE TITLE
Incompatible with Mongoid 5

### ISSUE THREAD

**Issue by dexterouschen** [artsy/mongoid_fulltext#23]
In Indexes/Indexable, alias_method is used before create_indexes is defined, so there goes the first error.

After I move alias_method to the bottom, undefined method error is gone, but index_specification method on each model is lost for some reason, so indexes can't be created.

create_indexes without mongoid_fulltext works.

**Comment by dblock** [comment]
I am assuming you use the latest 0.7.0. 

It would be great if you could help write a spec for this issue, I am happy to help fix.

**Comment by michalvalasek** [comment]
I installed the gem (0.7.0), run `rails server` and got this error:
```
/Users/michal/.rbenv/versions/2.2.1/gemsets/faq/gems/mongoid_fulltext-0.7.0/lib/mongoid/indexable.rb:5:in `alias_method': undefined method `create_indexes' for module `Mongoid::Indexable::ClassMethods' (NameError)
```

**Comment by Magi-KS** [comment]
having the same issue, dig through stuff and found that bothe mongoid_fulltext and mongoid have the same file in the same directory structure lib/mongoid/indexable.rb.
when mongoid gem require 'mongoid/indexable', the one in mongoid_fulltext is loaded first, causing the error.

**Comment by dblock** [comment]
Is there something about the order of includes? What comes first in your gemfile?

**Comment by Magi-KS** [comment]
mongoid first

**Comment by dblock** [comment]
Can someone try https://github.com/dblock/mongoid_fulltext/tree/fix-undefined-method please?

```
gem 'mongoid_fulltext', github: 'dblock/mongoid_fulltext', branch: 'fix-undefined-method'
```

**Comment by dblock** [comment]
cc: @Magi-KS

**Comment by Magi-KS** [comment]
works :+1:

**Comment by dblock** [comment]
Fixed in https://github.com/artsy/mongoid_fulltext/pull/24.

**Comment by dblock** [comment]
I've release 0.7.1 with this fix. Thanks for bringing this up.

**Comment by michalvalasek** [comment]
@dblock Thanks!
